@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedFinClient" as VersionedFinClient MODEL_COLOR
end box

[-> Model : undoFinClient()
activate Model

Model -> VersionedFinClient : undo()
activate VersionedFinClient

VersionedFinClient -> VersionedFinClient :resetData(ReadOnlyFinClient)
VersionedFinClient --> Model :
deactivate VersionedFinClient

[<-- Model
deactivate Model

@enduml
